index:
    path: /
    controller: App\Controller\CryptoController::index

admin:
    path: /admin
    controller: App\Controller\UserController::admin

recherche_avancer:
    path: /cryptos/recherche_avancer
    controller: App\Controller\CryptoController::cryptosRechercheAvancee